### ISSUE TITLE
Test coverage - async action processor

### ISSUE THREAD

**Issue by szoio** [simplesourcing/simplesagas#17]
Add test coverage for  the async action processor.

**Comment by wongelz** [comment]
I started looking into this. We may have to convert the Kafka consumer code to a Processor so that it is part of the Topology.

**Comment by szoio** [comment]
I agree. If it forms part of the topology it will be easier to test.
That's probably the right way to do it in any case.

**Comment by wongelz** [comment]
Currently a dead-end :( https://issues.apache.org/jira/browse/KAFKA-6989

**Comment by szoio** [comment]
That's too bad. What we have currently does work, but it steps outside the Kafka Streams world, so it's a) not that easy to test with the `TopologyTestDriver` and b) cannot offer the same consistency guarantee, though it might be sufficiently robust for pretty much any real application, provided the action itself is idempotent.
It may be possible to partially test with the TopologyTestDriver.
